// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9GV9KI6IvDrsROmQzgzRCL-0b4x2y4_w',
    appId: '1:205202750215:web:25c0250a836cc2d268e3a2',
    messagingSenderId: '205202750215',
    projectId: 'climbnotes-1e45f',
    authDomain: 'climbnotes-1e45f.firebaseapp.com',
    storageBucket: 'climbnotes-1e45f.appspot.com',
    measurementId: 'G-DQL1HPMCJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArIfCe9kM65Am00kl8hUVitK80lMr4Tdk',
    appId: '1:205202750215:android:85b6d62ec0502eff68e3a2',
    messagingSenderId: '205202750215',
    projectId: 'climbnotes-1e45f',
    storageBucket: 'climbnotes-1e45f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_iq7OEgfIIJuFBS1qPwHzUkCMZ8LEH4',
    appId: '1:205202750215:ios:aec6dd1e0d60093f68e3a2',
    messagingSenderId: '205202750215',
    projectId: 'climbnotes-1e45f',
    storageBucket: 'climbnotes-1e45f.appspot.com',
    iosBundleId: 'com.donotreplyme.climbnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu_iq7OEgfIIJuFBS1qPwHzUkCMZ8LEH4',
    appId: '1:205202750215:ios:aec6dd1e0d60093f68e3a2',
    messagingSenderId: '205202750215',
    projectId: 'climbnotes-1e45f',
    storageBucket: 'climbnotes-1e45f.appspot.com',
    iosBundleId: 'com.donotreplyme.climbnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9GV9KI6IvDrsROmQzgzRCL-0b4x2y4_w',
    appId: '1:205202750215:web:c3e2b91b9768c77868e3a2',
    messagingSenderId: '205202750215',
    projectId: 'climbnotes-1e45f',
    authDomain: 'climbnotes-1e45f.firebaseapp.com',
    storageBucket: 'climbnotes-1e45f.appspot.com',
    measurementId: 'G-ZJ0SE9F073',
  );
}
